// <auto-generated />
using CSWebApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CSWebApp.Migrations
{
    [DbContext(typeof(CSWebAppContext))]
    [Migration("20250509231330_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CSWebApp.Models.dbo_Table_3", b =>
                {
                    b.Property<string>("Aaaa")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Aaaa");

                    b.ToTable("dbo_Table_3");
                });
#pragma warning restore 612, 618
        }
    }
}
